spring.application.name=Backend-MediBridge
# Spring Application Name

# Si Render le da un puerto lo usa, si no, usa el tuyo en local
server.port=${PORT:8093}

# Spring DataSource Configuration (Si hay variables en la nube las usa, sino usa tu localhost)
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/medibridge-demo}
#spring.datasource.username=${DB_USER:postgres}
#spring.datasource.password=${DB_PASSWORD:1234}
#spring.datasource.driver-class-name=org.postgresql.Driver

# DEPLOYEADO
spring.datasource.url=jdbc:postgresql://ep-dawn-violet-ap60gaoh-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require

SPRING.DATASOURCE.USERNAME=neondb_owner
SPRING.DATASOURCE.PASSWORD=npg_0oAUtKDCLh7x

spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.database=postgresql
spring.jpa.show-sql=true

# Orígenes permitidos (Dejo tu localhost por defecto para cuando pruebes el front)
cors.allowed.origins=${CORS_ORIGIN:http://localhost:4200}

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=pe.edu.upc.vitalsync.medibridge.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Seguridad
app.jwt.secret=${JWT_SECRET:58074c3c5139b918dbbbf8e6345e7e22}
app.jwt.expiration=3600000